fix the file not found error for subprocess.call in CentOS 7   because nav start casue
	FileNotFoundError: [Errno 2] No such file or directory: 'alertengine.py': 'alertengine.py'

   However, This can be a security hazard though:
     https://docs.python.org/2/library/subprocess.html#frequently-used-arguments